In [1]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt

In [2]:
df = pd.read_csv('adult.csv')
df.head()

39          State-gov   77516   Bachelors   13        Never-married  \
0  50   Self-emp-not-inc   83311   Bachelors   13   Married-civ-spouse   
1  38            Private  215646     HS-grad    9             Divorced   
2  53            Private  234721        11th    7   Married-civ-spouse   
3  28            Private  338409   Bachelors   13   Married-civ-spouse   
4  37            Private  284582     Masters   14   Married-civ-spouse   

         Adm-clerical   Not-in-family   White     Male   2174   0   40  \
0     Exec-managerial         Husband   White     Male      0   0   13   
1   Handlers-cleaners   Not-in-family   White     Male      0   0   40   
2   Handlers-cleaners         Husband   Black     Male      0   0   40   
3      Prof-specialty            Wife   Black   Female      0   0   40   
4     Exec-managerial            Wife   White   Female      0   0   40   

    United-States   <=50K  
0   United-States   <=50K  
1   United-States   <=50K  
2   United-States   <=50K  
3            Cuba   <=50K  
4   United-States   <=50K

In [3]:
df.columns=['Age','Workclass','Fnlwgt','Education','Education_Num','Marital_Status','Occupation','Relationship','Race','Sex','Capital_Gain','Capital_Loss','Hours_per_week','Native_country','Income']

In [4]:
df.head()

Age          Workclass  Fnlwgt   Education  Education_Num  \
0   50   Self-emp-not-inc   83311   Bachelors             13   
1   38            Private  215646     HS-grad              9   
2   53            Private  234721        11th              7   
3   28            Private  338409   Bachelors             13   
4   37            Private  284582     Masters             14   

        Marital_Status          Occupation    Relationship    Race      Sex  \
0   Married-civ-spouse     Exec-managerial         Husband   White     Male   
1             Divorced   Handlers-cleaners   Not-in-family   White     Male   
2   Married-civ-spouse   Handlers-cleaners         Husband   Black     Male   
3   Married-civ-spouse      Prof-specialty            Wife   Black   Female   
4   Married-civ-spouse     Exec-managerial            Wife   White   Female   

   Capital_Gain  Capital_Loss  Hours_per_week  Native_country  Income  
0             0             0              13   United-States   <=50K  
1             0             0              40   United-States   <=50K  
2             0             0              40   United-States   <=50K  
3             0             0              40            Cuba   <=50K  
4             0             0              40   United-States   <=50K

In [5]:
df.shape

(32560, 15)

In [6]:
df.dtypes

Age                int64
Workclass         object
Fnlwgt             int64
Education         object
Education_Num      int64
Marital_Status    object
Occupation        object
Relationship      object
Race              object
Sex               object
Capital_Gain       int64
Capital_Loss       int64
Hours_per_week     int64
Native_country    object
Income            object
dtype: object

In [7]:
df.isnull().sum()

Age               0
Workclass         0
Fnlwgt            0
Education         0
Education_Num     0
Marital_Status    0
Occupation        0
Relationship      0
Race              0
Sex               0
Capital_Gain      0
Capital_Loss      0
Hours_per_week    0
Native_country    0
Income            0
dtype: int64

In [8]:
from sklearn.preprocessing import LabelEncoder

In [9]:
lb = LabelEncoder()
df['Workclass'] = lb.fit_transform(df['Workclass'])
df['Education'] = lb.fit_transform(df['Education'])
df['Marital_Status'] = lb.fit_transform(df['Marital_Status'])
df['Occupation'] = lb.fit_transform(df['Occupation'])
df['Relationship'] = lb.fit_transform(df['Relationship'])
df['Race'] = lb.fit_transform(df['Race'])
df['Sex'] = lb.fit_transform(df['Sex'])
df['Native_country'] = lb.fit_transform(df['Native_country'])
df['Income'] = lb.fit_transform(df['Income'])


In [10]:
df['Workclass'].value_counts()

4    22696
6     2541
2     2093
0     1836
7     1297
5     1116
1      960
8       14
3        7
Name: Workclass, dtype: int64

In [11]:
df['Education'].value_counts()


11    10501
15     7291
9      5354
12     1723
8      1382
1      1175
7      1067
0       933
5       646
14      576
6       514
2       433
10      413
4       333
3       168
13       51
Name: Education, dtype: int64

In [12]:
df['Marital_Status'].value_counts() 


2    14976
4    10682
0     4443
5     1025
6      993
3      418
1       23
Name: Marital_Status, dtype: int64

In [13]:
df['Occupation'].value_counts()


10    4140
3     4099
4     4066
1     3769
12    3650
8     3295
7     2002
0     1843
14    1597
6     1370
5      994
13     928
11     649
9      149
2        9
Name: Occupation, dtype: int64

In [14]:
df['Relationship'].value_counts()


0    13193
1     8304
3     5068
4     3446
5     1568
2      981
Name: Relationship, dtype: int64

In [15]:
df['Race'].value_counts()


4    27815
2     3124
1     1039
0      311
3      271
Name: Race, dtype: int64

In [16]:
df['Sex'].value_counts()


1    21789
0    10771
Name: Sex, dtype: int64

In [17]:
df['Income'].value_counts()

0    24719
1     7841
Name: Income, dtype: int64

In [18]:
df.head()

Age  Workclass  Fnlwgt  Education  Education_Num  Marital_Status  \
0   50          6   83311          9             13               2   
1   38          4  215646         11              9               0   
2   53          4  234721          1              7               2   
3   28          4  338409          9             13               2   
4   37          4  284582         12             14               2   

   Occupation  Relationship  Race  Sex  Capital_Gain  Capital_Loss  \
0           4             0     4    1             0             0   
1           6             1     4    1             0             0   
2           6             0     2    1             0             0   
3          10             5     2    0             0             0   
4           4             5     4    0             0             0   

   Hours_per_week  Native_country  Income  
0              13              39       0  
1              40              39       0  
2              40              39       0  
3              40               5       0  
4              40              39       0

In [19]:
x = df.iloc[:,:-1]
y = df.iloc [:,-1]
print(type(x),type(y))

<class 'pandas.core.frame.DataFrame'> <class 'pandas.core.series.Series'>


In [20]:
print(x.shape)
print(y.shape)

(32560, 14)
(32560,)


In [21]:
from sklearn.model_selection import train_test_split

In [22]:
x_tr,x_te,y_tr,y_te = train_test_split(x,y,test_size=0.25)
print(x_tr.shape)
print(x_te.shape)
print(y_tr.shape)
print(y_te.shape)

(24420, 14)
(8140, 14)
(24420,)
(8140,)


In [23]:
x.head()

Age  Workclass  Fnlwgt  Education  Education_Num  Marital_Status  \
0   50          6   83311          9             13               2   
1   38          4  215646         11              9               0   
2   53          4  234721          1              7               2   
3   28          4  338409          9             13               2   
4   37          4  284582         12             14               2   

   Occupation  Relationship  Race  Sex  Capital_Gain  Capital_Loss  \
0           4             0     4    1             0             0   
1           6             1     4    1             0             0   
2           6             0     2    1             0             0   
3          10             5     2    0             0             0   
4           4             5     4    0             0             0   

   Hours_per_week  Native_country  
0              13              39  
1              40              39  
2              40              39  
3              40               5  
4              40              39

In [24]:
y.head()

0    0
1    0
2    0
3    0
4    0
Name: Income, dtype: int32

### (i) Applying Decision Tree Classifier

In [25]:
from sklearn.tree import DecisionTreeClassifier
from sklearn.metrics import confusion_matrix,classification_report

In [26]:
m1  = DecisionTreeClassifier(criterion='gini',max_depth=7)
m1.fit(x_tr,y_tr)

DecisionTreeClassifier(max_depth=7)

In [27]:
ypred_m1 = m1.predict(x_te)
print(ypred_m1)
print('Training score',m1.score(x_tr,y_tr))
print('Testing score',m1.score(x_te,y_te))

[0 1 0 ... 0 0 0]
Training score 0.8613431613431614
Testing score 0.8502457002457002


In [28]:
cm_m1 = confusion_matrix(y_te,ypred_m1)
print(cm_m1)
print(classification_report(y_te,ypred_m1))

[[5821  295]
 [ 924 1100]]
              precision    recall  f1-score   support

           0       0.86      0.95      0.91      6116
           1       0.79      0.54      0.64      2024

    accuracy                           0.85      8140
   macro avg       0.83      0.75      0.77      8140
weighted avg       0.84      0.85      0.84      8140



### (ii) Applying RandomForest Classifier

In [29]:
from sklearn.ensemble import RandomForestClassifier

In [30]:
m2 = RandomForestClassifier(n_estimators=100,criterion='entropy',min_samples_split=15,max_depth=7)
m2.fit(x_tr,y_tr)

RandomForestClassifier(criterion='entropy', max_depth=7, min_samples_split=15)

In [31]:
ypred_m2 = m2.predict(x_te)
print(ypred_m2)
print('Training score',m2.score(x_tr,y_tr))
print('Testing score',m2.score(x_te,y_te))

[0 1 0 ... 0 0 0]
Training score 0.8585585585585586
Testing score 0.8514742014742015


In [32]:
cm_m2 = confusion_matrix(y_te,ypred_m2)
print(cm_m2)
print(classification_report(y_te,ypred_m2))

[[5879  237]
 [ 972 1052]]
              precision    recall  f1-score   support

           0       0.86      0.96      0.91      6116
           1       0.82      0.52      0.64      2024

    accuracy                           0.85      8140
   macro avg       0.84      0.74      0.77      8140
weighted avg       0.85      0.85      0.84      8140



### (iii)Applying Logistic Regression

In [33]:
from sklearn.linear_model import LogisticRegression

In [34]:
m3= LogisticRegression(solver='liblinear')
m3.fit(x_tr,y_tr)

LogisticRegression(solver='liblinear')

In [35]:
ypred_m3 = m3.predict(x_te)
print(ypred_m3)
print('Training score',m3.score(x_tr,y_tr))
print('Testing score',m3.score(x_te,y_te))

[1 0 0 ... 0 0 0]
Training score 0.7897624897624897
Testing score 0.7859950859950859


In [36]:
cm_m3 = confusion_matrix(y_te,ypred_m3)
print(cm_m3)
print(classification_report(y_te,ypred_m3))

[[5793  323]
 [1419  605]]
              precision    recall  f1-score   support

           0       0.80      0.95      0.87      6116
           1       0.65      0.30      0.41      2024

    accuracy                           0.79      8140
   macro avg       0.73      0.62      0.64      8140
weighted avg       0.77      0.79      0.76      8140



### (iv) Apply KNN Classification

In [37]:
from sklearn.neighbors import KNeighborsClassifier

In [38]:
m4 = KNeighborsClassifier(n_neighbors=13)
m4.fit(x_tr,y_tr)

KNeighborsClassifier(n_neighbors=13)

In [39]:
ypred_m4 = m4.predict(x_te)
print(ypred_m4)
print('Training score',m4.score(x_tr,y_tr))
print('Testing score',m4.score(x_te,y_te))

[0 0 0 ... 0 0 0]
Training score 0.8080262080262081
Testing score 0.7907862407862408


In [40]:
cm_m4 = confusion_matrix(y_te,ypred_m4)
print(cm_m4)
print(classification_report(y_te,ypred_m4))

[[5957  159]
 [1544  480]]
              precision    recall  f1-score   support

           0       0.79      0.97      0.87      6116
           1       0.75      0.24      0.36      2024

    accuracy                           0.79      8140
   macro avg       0.77      0.61      0.62      8140
weighted avg       0.78      0.79      0.75      8140



### (v)Applying SVC

In [41]:
from sklearn.svm import SVC

In [42]:
m5 = SVC(kernel='linear',C=1)
m5.fit(x_tr,y_tr)

SVC(C=1, kernel='linear')

In [43]:
ypred_m5 = m5.predict(x_te)
print(ypred_m5)
print('Training score',m5.score(x_tr,y_tr))
print('Testing score',m5.score(x_te,y_te))

[0 0 0 ... 0 0 0]
Training score 0.7974201474201474
Testing score 0.7932432432432432


In [44]:
cm_m5 = confusion_matrix(y_te,ypred_m5)
print(cm_m5)
print(classification_report(y_te,ypred_m5))

[[5841  275]
 [1408  616]]
              precision    recall  f1-score   support

           0       0.81      0.96      0.87      6116
           1       0.69      0.30      0.42      2024

    accuracy                           0.79      8140
   macro avg       0.75      0.63      0.65      8140
weighted avg       0.78      0.79      0.76      8140



In [ ]:
"""
(i) Decision tree- 85% accuracy
(ii)Random forest- 85% accuracy
(iii)KNN classification- 79% accuracy 
(iv)Logistic Regression- 79% accuracy 
(v)SVM- 79% accuracy
"""

# Therefore the model with highest accuracy is Random Forest and Decision Tree with an accuracy of 85%